// <auto-generated />
using System;
using Infrastructure.BoardGamesEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.BoardGamesEF.Migrations
{
    [DbContext(typeof(BoardGamesContext))]
    [Migration("20231018133224_add-game-event-registrations")]
    partial class addgameeventregistrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Het populaire handelsspel Catan in een nieuw jasje! Nu met nog meer spelbeleving! Lukt het jou om op Catan de belangrijkste macht te worden?",
                            Genre = 0,
                            ImageUri = "https://image.intertoys.nl/wcsstore/IntertoysCAS/images/catalog/full/1006506-e69938b2.jpg",
                            Is18Plus = false,
                            Name = "Catan",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Speel Monopoly Classic en maak kennis met de badeend, de Tyrannosaurus Rex en de pinguïn. Ga kopen en onderhandelen om de ultieme rijkdom te behalen.",
                            Genre = 2,
                            ImageUri = "https://image.intertoys.nl/wcsstore/IntertoysCAS/images/catalog/full/1557023-b23d0603.jpg",
                            Is18Plus = false,
                            Name = "Monopoly",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Verover het territorium van je vijanden in het strategische spel Risk! De worp van de dobbelstenen is jouw weg naar de overwinning!",
                            Genre = 0,
                            ImageUri = "https://image.intertoys.nl/wcsstore/IntertoysCAS/images/catalog/full/1387810-9348cdd6.jpg",
                            Is18Plus = false,
                            Name = "Risk",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Een speciale editie van Rummikub in een luxe, zwart blik! Ter ere van het 70-jarig bestaan van Rummikub heeft deze versie zware, zwarte stenen!",
                            Genre = 4,
                            ImageUri = "https://image.intertoys.nl/wcsstore/IntertoysCAS/images/catalog/thumb/1984456-04e5b2e1.jpg",
                            Is18Plus = true,
                            Name = "Rummikub",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Core.Domain.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("OrganizerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("Core.Domain.GameEventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameEventId");

                    b.HasIndex("UserId");

                    b.ToTable("GameEventRegistration");
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Domain.GameEvent", b =>
                {
                    b.HasOne("Core.Domain.User", "Organizer")
                        .WithMany("OrganisedGameEvents")
                        .HasForeignKey("OrganizerId");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Core.Domain.GameEventRegistration", b =>
                {
                    b.HasOne("Core.Domain.GameEvent", "GameEvent")
                        .WithMany("Registrations")
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.User", "User")
                        .WithMany("GameEventRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.GameEvent", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.Navigation("GameEventRegistrations");

                    b.Navigation("OrganisedGameEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
